name: Java CI

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=murremway_FoiApp
      - name: upload artifacts
        run: mkdir staging && cp target/*.war staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [build]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker run -i --rm --name foiapp -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install
      - name: Publish Docker image
        run: docker push $REPO
