name: Java CI

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          # GITHUB_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
      - name: upload artifacts
        run: mkdir staging && cp target/*.war staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
